# Generated by Django 2.1.3 on 2019-01-19 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=64)),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('correct_times', models.IntegerField(default=0)),
                ('correct_points', models.IntegerField(default=0)),
                ('cmp_cc_times', models.IntegerField(default=0)),
                ('cmp_cw_times', models.IntegerField(default=0)),
                ('cmp_wc_times', models.IntegerField(default=0)),
                ('cmp_ww_times', models.IntegerField(default=0)),
                ('cmp_cc_points', models.IntegerField(default=0)),
                ('cmp_cw_points', models.IntegerField(default=0)),
                ('cmp_wc_points', models.IntegerField(default=0)),
                ('cmp_ww_points', models.IntegerField(default=0)),
                ('rvl_cc_times', models.IntegerField(default=0)),
                ('rvl_cw_times', models.IntegerField(default=0)),
                ('rvl_wc_times', models.IntegerField(default=0)),
                ('rvl_ww_times', models.IntegerField(default=0)),
                ('rvl_cc_points', models.IntegerField(default=0)),
                ('rvl_cw_points', models.IntegerField(default=0)),
                ('rvl_wc_points', models.IntegerField(default=0)),
                ('rvl_ww_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=32)),
                ('lap', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('JOINING', 'Joining'), ('RUNNING', 'Running'), ('CLOSED', 'Closed')], max_length=8)),
                ('testing', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Quess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quess', models.CharField(choices=[('PASS', 'Pass'), ('CORRECT', 'Correct'), ('WRONG', 'Wrong')], max_length=8)),
                ('points', models.IntegerField(default=0)),
                ('correct', models.BooleanField(default=False)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowu2.Competitor')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=24)),
                ('group', models.CharField(max_length=24)),
                ('question', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=64)),
                ('correct', models.BooleanField(default=False)),
                ('correct_points', models.IntegerField(default=0)),
                ('cmp_cc_times', models.IntegerField(default=0)),
                ('cmp_cw_times', models.IntegerField(default=0)),
                ('cmp_wc_times', models.IntegerField(default=0)),
                ('cmp_ww_times', models.IntegerField(default=0)),
                ('cmp_cc_points', models.IntegerField(default=0)),
                ('cmp_cw_points', models.IntegerField(default=0)),
                ('cmp_wc_points', models.IntegerField(default=0)),
                ('cmp_ww_points', models.IntegerField(default=0)),
                ('rvl_cc_times', models.IntegerField(default=0)),
                ('rvl_cw_times', models.IntegerField(default=0)),
                ('rvl_wc_times', models.IntegerField(default=0)),
                ('rvl_ww_times', models.IntegerField(default=0)),
                ('rvl_cc_points', models.IntegerField(default=0)),
                ('rvl_cw_points', models.IntegerField(default=0)),
                ('rvl_wc_points', models.IntegerField(default=0)),
                ('rvl_ww_points', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REPLIED', 'Replied')], max_length=8)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowu2.Competitor')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REPLIED', 'Replied'), ('JUDGED', 'Judged'), ('FINISHED', 'Finished')], max_length=8)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowu2.Match')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowu2.Question')),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowu2.Round'),
        ),
        migrations.AddField(
            model_name='quess',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowu2.Reply'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowu2.Match'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowu2.Question'),
        ),
    ]
